"""Initial migration

Revision ID: b204e4367b96
Revises: 
Create Date: 2024-10-13 20:20:25.532598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b204e4367b96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=80),
               existing_nullable=False)
        # Remove the alteration of password_hash column
        # batch_op.alter_column('password_hash',
        #        existing_type=sa.VARCHAR(length=256),
        #        type_=sa.String(length=128),
        #        existing_nullable=True,
        #        nullable=False)

    with op.batch_alter_table('casino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=False, server_default=''))
        batch_op.drop_column('last_collection')
        batch_op.drop_column('collection_interval')
        batch_op.drop_column('next_collection')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('coins')

    with op.batch_alter_table('casino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_collection', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('collection_interval', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('last_collection', sa.DATETIME(), nullable=True))
        batch_op.drop_column('website')

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Remove the alteration of password_hash column
        # batch_op.alter_column('password_hash',
        #        existing_type=sa.String(length=128),
        #        type_=sa.VARCHAR(length=256),
        #        existing_nullable=False,
        #        nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
